### ISSUE TITLE
Framing actions against Pactmates carry no consequences

### ISSUE THREAD

**Issue by nevill-spb** [tnevolin/thinker-doer#51] opened 2020-11-08 15:12 UTC
Issue:

Be pacted with a computer player. Commence Probe Team action against the same computer player, and frame someone else. Get caught. The pactmate will say they would renounce the pact immediately, but won't actually do anything.

(also, in MP a window would pop up asking the current player - the one commencing the probe operation - what to do on behalf of the framed player. While making a decision for another player is weird design, it might actually be workin as intended, since probing actions require an immediate reaction. But it probably shouldn't be prompting about it when your two factions are already at Vendetta. Just mentioning this in case you will be looking at the code)

During the act (probe team is caught)
![FrameJob_1](https://user-images.githubusercontent.com/73173288/98468492-bef9b880-21eb-11eb-9eb8-1c3131024ed9.jpg)
Stated consequences:
![FrameJob_4](https://user-images.githubusercontent.com/73173288/98469031-59f39200-21ee-11eb-8526-58cdad05dcd2.jpg)
Actual consequences (nothing):
![FrameJob_2](https://user-images.githubusercontent.com/73173288/98468496-c15c1280-21eb-11eb-80ea-672842cbc903.jpg)
![FrameJob_3](https://user-images.githubusercontent.com/73173288/98468497-c1f4a900-21eb-11eb-81e4-b6c934898b41.jpg)

This allows you to attempt actions against a pact mate with impunity at somewhat reduced chance of success.

Doing the same action without a framejob would cause the relationship to degrade correctly, with a corresponsing decrease in Integrity.

**Comment by tnevolin** [comment] 2020-11-08 16:24
OMG. Where do you dig them out from? I was never even aware of this one.
😁
Will look at it.

**Comment by tnevolin** [comment] 2021-03-31 11:00
I have tested this and it worked as designed. Both factions (penetrated and framed) declared vendetta on me.
Maybe you indeed caught a bug but there should be other conditions to it. Does it happen only in MP?

**Comment by tnevolin** [comment] 2021-08-14 23:18
Closing as unable to reproduce. See my last comment above.

**Closed by tnevolin** 2021-08-14 23:18 UTC
Labels: bug
