### ISSUE TITLE
wrong string from label.txt displayed for Reactor

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#70] opened 2021-04-24 03:42 UTC
When I got Fusion Power, this queer text string "Also the # of Workers, Talents, Drones, and Specialists." was displayed in the tech description window.  It is also displayed in the upper right corner of the unit design workshop, in the Reactor box, if I have a Fusion reactor.  Not with Fission.  The string is part of line 820 in labels.txt, and is the same as the original game:

`CITIZENS: Shows the population of this base.^Also the # of Workers, Talents, Drones, and Specialists.
`

So it seems somehow, you're gaining the portion after ^ and displaying it.

**Comment by tnevolin** [comment] 2021-04-24 04:01
Interesting. I don't see anything like that. Don't remember ever touching labels.txt.
Would you mind to try latest version clean install?

**Comment by bvanevery** [comment] 2021-04-24 05:14
labels.txt is something you ship in your distro though.  I'm installing #228 now, but I'm not sure what a "clean" install would mean.  I always just drop your files on top of the previous installation.  If you haven't added or deleted files, then they'll always get overwritten.  I'm always a little fuzzy on the significance of the various .tmp files.  Those got created on 10-5-2020, quite awhile ago.  Since I've never seen this queer text string before, I'm not inclined to mess with the .tmp files.

Guess in my next game, we'll see if I see this again.  Who knows, maybe it was a fluke.

**Comment by tnevolin** [comment] 2021-04-24 14:42
I don't know what is clean install either. Probably wipe out directory and install it from GOG and further.
😊
Don't bother with this unless you see it repeatedly.

**Comment by bvanevery** [comment] 2021-04-25 00:16
It happened again.  The weird string is being used in place of "Fusion Reactor".  This is the 3rd distinct place I've seen the wrong string used.
![wrong fusior reactor string](https://user-images.githubusercontent.com/734930/115976234-e47c4380-a539-11eb-9131-33b35fe6c9ad.jpg)

**Comment by bvanevery** [comment] 2021-04-25 00:40
Surely related are the strange single letter insertions in unit names.  I saw this last time as well, but different single letters were used.  This seems to indicate that the problem is some kind of string corruption.  Could you have made a pointer at something wrong?
![random letters inserted in unit names](https://user-images.githubusercontent.com/734930/115976560-34103e80-a53d-11eb-9de4-2aa077a63de6.jpg)

**Comment by tnevolin** [comment] 2021-04-25 02:47
I understand the problem but don't observe it and cannot reproduce. That seems like broken text files or something. Cannot tell without evidence in my hands.
One thing you could do is package whole game directory and attach it here if size allows. I believe it is completely self sufficient.
![fusion](https://user-images.githubusercontent.com/830161/115978657-0207d800-a54f-11eb-8b96-acf601a5d851.png)

**Comment by bvanevery** [comment] 2021-04-25 04:02
You loaded my save and didn't see the behavior?

**Comment by bvanevery** [comment] 2021-04-25 04:24
Clean install of SMACX.  Installed WTP 228 over that.  Loaded the .sav.  Don't see the queer string anymore.  Do still see the unit name corruptions, but that's probably just part of the .sav.

**Comment by tnevolin** [comment] 2021-04-25 18:38
You didn't give me any save. I just tried to discover it myself. If you give me one right before you have discovered this tech I can try it too.

**Comment by tnevolin** [comment] 2021-04-25 18:38
Great to hear clean install did it. Let me know if you see any more name corruption in new games.

**Comment by bvanevery** [comment] 2021-04-25 18:54
My bad, I gave you a save of the foil probe team issue, in the other Issue thread.  Didn't think about how I was responding to 2 Issues.

**Comment by bvanevery** [comment] 2021-04-25 19:05
In my previous reporting about the clean install, I believe I started the wrong .exe.  I used a Shortcut on my desktop that I had helpfully relabled "WTP 228", without actually changing it to point to terranx_mod.exe.  So all bets on "things being ok" are off.  I'll know by this evening though.

Got tipped off to my error, when I didn't have any Formers starting up.

**Comment by tnevolin** [comment] 2021-08-14 23:06
I think I have found the problem and fixed that. Don't remember in which release, though. Still going to close it.

**Closed by tnevolin** 2021-08-14 23:06 UTC
