### ISSUE TITLE
foil probe teams return to landlocked coastal bases

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#65] opened 2021-04-21 01:46 UTC
I find that when I have a landlocked base on a small inland lake, my foil probe teams inevitably end up being returned there when they accomplish their missions.  Although it's 'nice' not to lose the unit completely, a foil probe team in a landlocked base is usually not very useful.  I could swear that someone came up with a solution for this problem.  Was it Scient?

**Comment by tnevolin** [comment] 2021-04-21 03:06
It was me. Apparently I may not complete it 100%. Please send me a save. I'll check it out.

**Comment by bvanevery** [comment] 2021-04-21 07:17
[H'minee of the Caretakers, 2240.zip](https://github.com/tnevolin/thinker-doer/files/6348794/H.minee.of.the.Caretakers.2240.zip)

Note foil probe team in Vinculum.  When it got stuck there, that was one of my northeasternmost cities.  It ran a mission on the Cultists to the northeast.

**Comment by tnevolin** [comment] 2021-04-21 13:13
Hmm. I would like the save before that happens. Let me see if I can recreate it with editor.

**Comment by tnevolin** [comment] 2021-04-21 13:33
I have tested it in my current code version and it work as designed. Probe returns to closest base in region (sea or coastal). If no such base exists it is destroyed.
Would be interesting to see at the save before the action to debug it if it really happened like that.

**Comment by bvanevery** [comment] 2021-04-21 17:35
It'll need to wait until it happens again.  Scient gave me this nifty thing where I have continuous saves in order to track bugs.  Unfortunately that's for the stock binary.  I don't have continuous WTP saves.

**Comment by tnevolin** [comment] 2021-04-21 17:39
Can it be integrated?
I also tried to simulate it directly with editor and it works as designed - probe never appears in different region.

**Comment by bvanevery** [comment] 2021-04-21 19:19
Scient actually gave me a version of OpenSMACX, I'm technically not running a stock binary.  But he said all he added in, was this save feature.  So I believe he could achieve this in a WTP binary or Thinker, in principle.  In practice, it sounds like a chore and maybe he'd want some legwork / help with getting that code into your repo.

**Comment by tnevolin** [comment] 2021-04-21 20:53
If he show me the patch I can reproduce it.

**Comment by bvanevery** [comment] 2021-04-25 02:51
Here's a landlocked cruiser probe team.  This was definitely the nearest base to where it did its action.  But it's not reachable by sea.  At least this time it'll actually have something to do, against the Hive.
![landlocked cruiser probe](https://user-images.githubusercontent.com/734930/115978715-73e02180-a54f-11eb-9f01-44408ec1ef0b.jpg)
[Cha Dawn of the Planet Cult, 2224.zip](https://github.com/tnevolin/thinker-doer/files/6371152/Cha.Dawn.of.the.Planet.Cult.2224.zip)

**Comment by tnevolin** [comment] 2021-04-25 03:57
That normally happens in unpatched version of the game. I suspect there could be something with your binaries based on your "Fusion Reactor" messed up too. I guess the only way to know for sure is either for you to install GOG SMACX + my mod in empty folder and then copy your saves and try again. OR to pack the whole game directory and send it to me either here or some other way.

**Comment by bvanevery** [comment] 2021-04-25 04:26
Well I've got a clean install + WTP 228 on top of it now.  So we'll see.

**Comment by tnevolin** [comment] 2021-08-14 23:07
I am going to close it as I distinctly remember working on it and fixing it.

# Version 179

* FIX: Probe expelled from other faction territory was sent to largest population base which could be not appropriate for sea probes. Now probes are sent to **closest** base and for sea probes they also should be connected to same region so it should not get stranded on land or magically appear in another ocean. If such base cannot be found the probe is killed.

**Closed by tnevolin** 2021-08-14 23:07 UTC

**Comment by bvanevery** [comment] 2021-08-28 23:52
Version 259.  You didn't fix it.  You may have _tried_ to fix it, but...
[Santiago of the Spartans, 2219.zip](https://github.com/tnevolin/thinker-doer/files/7071670/Santiago.of.the.Spartans.2219.zip)
![stuck on a lake](https://user-images.githubusercontent.com/734930/131233708-d2df9d9b-757d-4011-8643-b7816386fa71.jpg)

I would note that completing a probe team mission against an enemy, is not the same circumstance as being sent home from a territory that one has a treaty with.  Maybe your fix went down 1 code path and not another.

It would be appropriate to reopen this Issue, until it is verified by me as fixed.  Although to some extent, that will be proving a negative.  Then again, any "lake" city at the extreme of an empire, will produce the bug, so it may not be hard to check that in some game.  As long as I remember to look for the behavior when doing a mission near a "lake".

**Comment by tnevolin** [comment] 2021-08-29 16:25
260
This one I fixed but cannot guarantee there are no other cases due to convoluted programming.

**Comment by bvanevery** [comment] 2021-08-29 17:54
[Santiago of the Spartans, 2220.zip](https://github.com/tnevolin/thinker-doer/files/7072979/Santiago.of.the.Spartans.2220.zip)

![to the capitol](https://user-images.githubusercontent.com/734930/131260408-c8949964-1141-49f4-b266-a1aa215c1fb4.jpg)
Huh, I got a dialog box saying it had been sent to Sparta Command, and indeed it is sent to Sparta Command.  Not 100% sure if this city was far enough away to be otherwise trying to go for the "lake" city.  I will try a few more turns farther afield.

**Comment by tnevolin** [comment] 2021-08-29 20:26
Is Sparta Command connected to the ocean probe was in? If so then it is the easiest hack I did for their sloppy development.
They are sending probe to the nearest base. Then for sea probes they also check that this base is also a port. If it is - probe is sent there regardless whether this port is of the same ocean. I see a generic reasoning of this lazy development: at least it goes to some port and maybe can continue operations there.
Then, if this base is not a port they scan all own bases from top and find the first one connected to this ocean. So it will be Sparta Command in your case.

I did a very simple fix - skip checking for nearest base is a port and instead just go directly to scan routine. At least this way probe stays in same ocean. Can get far from operation place, though.

**Comment by bvanevery** [comment] 2021-08-29 21:31
Sparta Command is part of this ocean, but there are bases immediately in its vicinity that are closer.  It's not a big deal in _this_ part of the ocean.  However, it's a big, worldwide ocean, and there's this whole side of the continent that is not directly accessible.  Think like having to go around Cape Horn before the Suez Canal existed.  It would not be at all fun to have probe teams sent all the way back to a city on the wrong side of a massive continent.

Also, tactically, if I make a forward base deeper into enemy waters, such as by taking over an enemy base, I should not be penalized for that.  My team should be going back to my forward base, not all the way back to the 1st city I ever made, because it happened to be on a world accessible coastline.

**Comment by tnevolin** [comment] 2021-08-29 23:13
261
Here.

**Comment by bvanevery** [comment] 2021-08-30 03:54
[Santiago of the Spartans, 2225.zip](https://github.com/tnevolin/thinker-doer/files/7074015/Santiago.of.the.Spartans.2225.zip)
Instead of going back to Sparta Command, goes back to Training Camp, which is the closest city with ocean access.  Doesn't go to the "lake" city.  Congrats!
