### ISSUE TITLE
artifact cannot be captured

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#96] opened 2021-08-04 04:31 UTC
![artifact cannot be captured](https://user-images.githubusercontent.com/734930/128122064-891571c3-c3d7-4752-9186-425c5dbe75f2.jpg)
I have a Treaty with the Data Angels.  There is no other unit in the square with their Artifact.  I find no indication that WTP or Thinker deliberately changed the rules on capturing artifacts.  The Datalinks say you may do so.
[Svensgaard of the Pirates, 2144.zip](https://github.com/tnevolin/thinker-doer/files/6928595/Svensgaard.of.the.Pirates.2144.zip)

![artifact zones of control](https://user-images.githubusercontent.com/734930/128122351-c5f2f825-a3a2-4dc1-8a33-debb1dd5b970.jpg)
Realized when trying to move in other directions, that there are 2 previously unseen units exerting zones of control.  Wonder if this has something to do with it.  Could swear I've captured artifacts just fine in other games.

Or is it because the Artifact is in its home territory?  If intended, that's not stock game behavior.  In any event the Datalinks don't give any detail about such a special case, nor do any of the .md files I looked at.

**Comment by tnevolin** [comment] 2021-08-10 17:29
I didn't do anything about capturing artifacts, specifically. Could you just not move to this tile because of ZOC as you mentioned?

**Comment by tnevolin** [comment] 2021-08-10 17:33
I have tested it in different configuration and am able to capture it without problems. Please attach save or test it to confirm the bug. Otherwise, let's close it as unreproducible issue.

**Comment by bvanevery** [comment] 2021-08-10 20:35
The attached file is above in the text.  Look closely.

**Comment by tnevolin** [comment] 2021-08-10 22:44
254

**Closed by tnevolin** 2021-08-10 22:44 UTC
